/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package MainDialog;

import java.awt.HeadlessException;
import javax.swing.JOptionPane;
import java.sql.*;
import java.util.logging.*;

/**
 *
 * @author ASUS
 */
public class ForgetPassword extends javax.swing.JDialog {

    /**
     * Creates new form ForgetPassword
     */
    public ForgetPassword(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public boolean cekEmail(String Email){
        String sqlcon = "select * from user";
        try{
            ResultSet cek = Main.mainConnectionDB.con.createStatement().executeQuery(sqlcon);
            while(cek.next()){
                if(Email.equals(cek.getString("email"))){
                    return true;
                }
            }
        }catch(SQLException ex){
            System.out.print(ex.toString());
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        femail = new javax.swing.JTextField();
        fkode = new javax.swing.JTextField();
        fkirim = new javax.swing.JButton();
        fpassword = new javax.swing.JPasswordField();
        freset = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        femail.setBorder(null);
        getContentPane().add(femail, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 140, 200, 40));

        fkode.setBorder(null);
        getContentPane().add(fkode, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 240, 200, 30));

        fkirim.setContentAreaFilled(false);
        fkirim.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fkirimActionPerformed(evt);
            }
        });
        getContentPane().add(fkirim, new org.netbeans.lib.awtextra.AbsoluteConstraints(332, 140, 90, 30));

        fpassword.setBorder(null);
        getContentPane().add(fpassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 330, 200, 30));

        freset.setContentAreaFilled(false);
        freset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                fresetActionPerformed(evt);
            }
        });
        getContentPane().add(freset, new org.netbeans.lib.awtextra.AbsoluteConstraints(85, 410, 230, 60));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("X");
        jLabel1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel1MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 0, 60, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/forgotpass.jpeg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 694));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void fkirimActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fkirimActionPerformed
        // TODO add your handling code here:
        if(femail.getText().length() > 0){
            if(cekEmail(femail.getText())){
            String otp = Main.passEncrypt.generateOTP(6);

                //try write to db
                try{ 
                    String sql = "UPDATE user set forgotPassCode = ? where email = ?"; 
                    Main.mainConnectionDB.pst = Main.mainConnectionDB.con.prepareStatement(sql);
                    Main.mainConnectionDB.pst.setString(1, otp);
                    Main.mainConnectionDB.pst.setString(2, femail.getText());

                    Main.mainConnectionDB.pst.executeUpdate();
                    //dbConnect.pst.execute
                    Main.sendEmail.sendEmailForgotPass(femail.getText(), otp);
                    System.out.println("Mau update password");
                    JOptionPane.showMessageDialog(this, "Kode otp telah dikirim ke email anda");
                }catch(HeadlessException | SQLException ex){
                    System.out.println("Errornya adalah " + ex.getMessage());
                }
            }else{
                femail.setText("");
                JOptionPane.showMessageDialog(this, "Email tidak terdaftar");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Anda belum input email");
        }
    }//GEN-LAST:event_fkirimActionPerformed

    private void fresetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_fresetActionPerformed
        // TODO add your handling code here:
        
        if(femail.getText().length() > 0){
            if(fkode.getText().length() > 0){
                if(fpassword.getText().length() > 0){
                    try{
                        Main.mainConnectionDB.pst = Main.mainConnectionDB.con.prepareStatement("SELECT forgotPassCode FROM user WHERE email = ?");
                        Main.mainConnectionDB.pst.setString(1, femail.getText());
                        Main.mainConnectionDB.rs = Main.mainConnectionDB.pst.executeQuery();
                        String dataForgotPass = "";
                        while(Main.mainConnectionDB.rs.next()){
                            dataForgotPass = Main.mainConnectionDB.rs.getString("forgotPassCode");
                        }
                            String salt = Main.passEncrypt.getSaltvalue(6);
                            if(fkode.getText().equals(dataForgotPass)){
                                Main.mainConnectionDB.pst = Main.mainConnectionDB.con.prepareStatement("UPDATE user set forgotPassCode = ?, password = ?, salt = ? where email =?");
                                Main.mainConnectionDB.pst.setString(1, null);
                                Main.mainConnectionDB.pst.setString(2, Main.passEncrypt.generateSecurePassword(fpassword.getText(), salt));
                                Main.mainConnectionDB.pst.setString(3, salt);
                                Main.mainConnectionDB.pst.setString(4, femail.getText());
                                Main.mainConnectionDB.pst.executeUpdate();
                                System.out.println("update password berhasil");
                                JOptionPane.showMessageDialog(this, "Password berhasil diganti");
                                dispose();
                            }else{
                                System.out.println("otp beda, update gagal");
                            }
                    } catch (SQLException ex) {
                        Logger.getLogger(ForgetPassword.class.getName()).log(Level.SEVERE, null, ex);
                    }
                }else{
                    JOptionPane.showMessageDialog(this, "Anda belum input password baru");
                }
            }else{
                JOptionPane.showMessageDialog(this, "Anda belum input kode");
            }
        }else{
            JOptionPane.showMessageDialog(this, "Anda belum input email");
        }
        
        
        
        
    }//GEN-LAST:event_fresetActionPerformed

    private void jLabel1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel1MouseClicked
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_jLabel1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ForgetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ForgetPassword dialog = new ForgetPassword(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField femail;
    private javax.swing.JButton fkirim;
    private javax.swing.JTextField fkode;
    private javax.swing.JPasswordField fpassword;
    private javax.swing.JButton freset;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
