/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package MainDialog;

import java.awt.HeadlessException;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author anoth
 */
public class Register extends javax.swing.JDialog {

    /**
     * Creates new form Register
     */
    public Register(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }
    
    public static boolean cekOTP(String otp){
        try
        {
            Main.mainConnectionDB.pst = Main.mainConnectionDB.con.prepareStatement("SELECT registCode FROM user WHERE email = ?");
            Main.mainConnectionDB.pst.setString(1, email.getText());
            Main.mainConnectionDB.rs = Main.mainConnectionDB.pst.executeQuery();
            String datadb = "";
            while(Main.mainConnectionDB.rs.next()){
                datadb = Main.mainConnectionDB.rs.getString("registCode");
            }
            
            if(otp.equals(datadb)){
                Main.mainConnectionDB.pst = Main.mainConnectionDB.con.prepareStatement("UPDATE user set userActivation = ?, registCode = ? where email =?");
                Main.mainConnectionDB.pst.setInt(1, 1);
                Main.mainConnectionDB.pst.setString(2, null);
                Main.mainConnectionDB.pst.setString(3, email.getText());
                Main.mainConnectionDB.pst.executeUpdate();
                System.out.println("update berhasil");
                return true;
            }else{
                System.out.println("otp beda, update gagal");
                return false;
            }
        } catch (SQLException ex) {
            Logger.getLogger(Register.class.getName()).log(Level.SEVERE, null, ex);
        }
        return false;
    }
    
    public boolean cekUsername(String usernameRegist){
        String sqlcon = "select * from user";
                
        try{
            ResultSet cek = Main.mainConnectionDB.con.createStatement().executeQuery(sqlcon);
            while(cek.next()){
                if(usernameRegist.equals(cek.getString("username"))){
                    return true;
                }
            }
        }catch(SQLException ex){
            System.out.print(ex.toString());
        }
        return false;
    }
    
    public boolean cekEmail(String emailRegist){
        String sqlcon = "select * from user";
                
        try{
            ResultSet cek = Main.mainConnectionDB.con.createStatement().executeQuery(sqlcon);
            while(cek.next()){
                if(emailRegist.equals(cek.getString("email"))){
                    return true;
                }
            }
        }catch(SQLException ex){
            System.out.print(ex.toString());
        }
        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel2 = new javax.swing.JLabel();
        back = new javax.swing.JButton();
        email = new javax.swing.JTextField();
        username = new javax.swing.JTextField();
        password = new javax.swing.JPasswordField();
        repassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        btnRegis = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Segoe UI Black", 1, 24)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("X");
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 0, 40, 30));

        back.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        back.setText("Back");
        back.setContentAreaFilled(false);
        back.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backActionPerformed(evt);
            }
        });
        getContentPane().add(back, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 110, 30));

        email.setBackground(new java.awt.Color(248, 249, 251));
        email.setBorder(null);
        getContentPane().add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 300, 260, 30));

        username.setBackground(new java.awt.Color(248, 249, 251));
        username.setBorder(null);
        username.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernameActionPerformed(evt);
            }
        });
        getContentPane().add(username, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 190, 260, 30));

        password.setBackground(new java.awt.Color(249, 254, 251));
        password.setBorder(null);
        password.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordActionPerformed(evt);
            }
        });
        getContentPane().add(password, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 400, 260, 40));

        repassword.setBackground(new java.awt.Color(249, 254, 251));
        repassword.setBorder(null);
        repassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repasswordActionPerformed(evt);
            }
        });
        getContentPane().add(repassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 510, 270, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/project2.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 440, 700));

        btnRegis.setContentAreaFilled(false);
        btnRegis.setBackground(new java.awt.Color(85, 85, 85));
        btnRegis.setFont(new java.awt.Font("Wide Latin", 1, 14)); // NOI18N
        btnRegis.setForeground(new java.awt.Color(255, 255, 255));
        btnRegis.setText("REGISTER");
        btnRegis.setBorder(null);
        btnRegis.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisActionPerformed(evt);
            }
        });
        getContentPane().add(btnRegis, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 590, 220, 60));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void usernameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernameActionPerformed

    private void btnRegisActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisActionPerformed
        if(username.getText().length() > 0){
            if(email.getText().length() > 0){
                if(password.getText().length() > 0 && repassword.getText().length() > 0){
                    if(password.getText().equalsIgnoreCase(repassword.getText())){
                        if(cekUsername(username.getText())){
                            JOptionPane.showMessageDialog(null, "Username ini telah digunakan",
                            "Warning", JOptionPane.ERROR_MESSAGE);
                            username.setText("");
                        }else{
                            if(cekEmail(email.getText())){
                            JOptionPane.showMessageDialog(null, "Email ini telah digunakan",
                            "Warning", JOptionPane.ERROR_MESSAGE);
                            email.setText("");
                            }else{
                                String salt = Main.passEncrypt.getSaltvalue(6);
                                String otp = Main.passEncrypt.generateOTP(6);
                                String sql = "insert into user(username, email, password, salt, userActivation, registCode) values (?, ?, ?, ?, ?, ?)";                           
                                try{ 
                                    Main.mainConnectionDB.pst = Main.mainConnectionDB.con.prepareStatement(sql);
                                    Main.mainConnectionDB.pst.setString(1, username.getText());
                                    Main.mainConnectionDB.pst.setString(2, email.getText());
                                    Main.mainConnectionDB.pst.setString(3, Main.passEncrypt.generateSecurePassword(password.getText(), salt));
                                    Main.mainConnectionDB.pst.setString(4, salt);//salt
                                    Main.mainConnectionDB.pst.setInt(5, 0);
                                    Main.mainConnectionDB.pst.setString(6, otp);
                                    Main.mainConnectionDB.pst.executeUpdate();
                                    Main.sendEmail.sendEmailRegist(email.getText(), otp);
                                    System.out.println("Insert data user berhasil !");
                                    JOptionPane.showMessageDialog(this, "Kode OTP telah dikirim ke email kamu");
                                    
                                }catch(HeadlessException | SQLException ex){
                                    System.out.println("Errornya adalah " + ex.getMessage());
                                }
                                
                                MainDialog.KodeOTP dialogOTP = new MainDialog.KodeOTP(null, true);
                                dialogOTP.setVisible(true);
                            }
                        }
                    }else{
                        JOptionPane.showMessageDialog(null, "Password dan Confirm Password berbeda",
                "Coba Lagi", JOptionPane.INFORMATION_MESSAGE);
                        password.setText("");
                        repassword.setText("");
                    }
                }else{
                    JOptionPane.showMessageDialog(null, "Kamu belum input password",
                "Coba Lagi", JOptionPane.INFORMATION_MESSAGE);
                }
            }else{
                JOptionPane.showMessageDialog(null, "Kamu belum input email",
                "Coba Lagi", JOptionPane.INFORMATION_MESSAGE);
            }
        }else{
            JOptionPane.showMessageDialog(null, "Kamu belum input username",
                "Coba Lagi", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_btnRegisActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        dispose();
    }//GEN-LAST:event_jLabel2MouseClicked

    private void passwordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordActionPerformed

    private void repasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repasswordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repasswordActionPerformed

    private void backActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backActionPerformed
        MainDialog.LoginRegister login = new MainDialog.LoginRegister(null, true);
        dispose();
        login.setVisible(true);
    }//GEN-LAST:event_backActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try
        {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels())
            {
                if ("Nimbus".equals(info.getName()))
                {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex)
        {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex)
        {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex)
        {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex)
        {
            java.util.logging.Logger.getLogger(Register.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                Register dialog = new Register(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton back;
    private javax.swing.JButton btnRegis;
    public static javax.swing.JTextField email;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField password;
    private javax.swing.JPasswordField repassword;
    private javax.swing.JTextField username;
    // End of variables declaration//GEN-END:variables
}
